version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: loc-postgres
    environment:
      TZ: UTC
      POSTGRES_DB: my_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    # get ip address for connect to pgadmin
    # docker inspect loc-postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: loc-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  mongo:
    image: mongo:5.0
    container_name: loc-mongo
    environment:
      TZ: UTC
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db

  redis:
    image: redis:3-alpine
    container_name: loc-redis
    environment:
      TZ: UTC
    ports:
      - '6379:6379'

  app:
    container_name: loc-app
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile
    command: "yarn start:dev"
    ports:
      - '8080:8080'
    networks:
      - nestjs-network
    volumes:
      - ./usr/src/app
      - ./usr/src/app/node_modules
    restart: unless-stopped

networks:
  nestjs-network:
