version: '3.8'

services:
  postgres:
    image: postgres
    container_name: loc-postgres
    logging:
      driver: none
    environment:
      TZ: UTC
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  mongo:
    image: mongo:5.0
    container_name: loc-mongo
    logging:
      driver: none
    environment:
      TZ: UTC
    ports:
      - '27017:27017'

  redis:
    image: redis:3-alpine
    container_name: loc-redis
    logging:
      driver: none
    environment:
      TZ: UTC
    ports:
      - '6379:6379'

  app:
    container_name: loc-app
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile
    command: "yarn start:dev"
    ports:
      - '8080:8080'
    networks:
      - nestjs-network
    volumes:
      - ./usr/src/app
      - ./usr/src/app/node_modules
    restart: unless-stopped

networks:
  nestjs-network:
