name: 🐛 Bug Report
description: File a bug report here
title: "[BUG]: "
labels: ["bug"]
assignees: ["rudemex"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!!!

  - type: checkboxes
    id: new-bug
    attributes:
      label: Make sure these boxes are checked before submitting your issue, thank you!
      options:
        - label: You are using NodeJs 14 or higher?
          required: false
        - label: You have installed all dependencies and tools listed in the documentation?
          required: false
        - label: You have searched the existing issues if someone has already asked the same issue?
          required: false
        - label:  You have read the documentation?
          required: false
        - label: Is not a programming question.
          required: true
        - label: You are using latest code of Starter?
          required: false

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Tell us what bug you encountered and what should have happened
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: Please write the steps in a list form
    validations:
      required: true

  - type: dropdown
    id: versions
    attributes:
      label: Which version of the app are you using?
      description: If this issue is occurring on more than 1 version of the app, select the appropriate versions.
      multiple: true
      options:
        - v1.2.3
        - v1.2.2
        - v1.2.1
        - v1.2.0
        - v1.1.11
        - v1.1.10
        - v1.1.9
        - v1.1.8
        - v1.1.7
        - v1.1.6
        - v1.1.5
        - v1.1.4
        - v1.1.3
        - v1.1.2
        - v1.1.1
        - v1.1.0
        - v1.0.3
        - v1.0.2
        - v1.0.1
        - v1.0.0
        - v1.0.0-beta.2
        - v1.0.0-beta.1
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Provide any additional information such as logs, screenshots, likes, scenarios in which the bug occurs so that it facilitates resolving the issue.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: Read the [Code of Conduct](https://github.com/rudemex/nestjs-starter/blob/master/.github/CODE_OF_CONDUCT.md) first.
      options:
        - label: I agree to follow the Code of Conduct
          required: true
